config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :new, :show, :create, :edit, :update]
  resources :car_categories, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :new, :show, :create]
  resources :rentals, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  
end

app/models/subsidiary.rb
class Subsidiary < ApplicationRecord
  validates :name, :cnpj, :adress, presence: true
  validates :name, :cnpj, uniqueness: true
  validates :cnpj, format: { with: /\A^\d{2,3}\.\d{3}\.\d{3}\/\d{4}\-\d{2}$\z/, message: 'com formato inválido' }
  validate :cnpj_must_be_valid

  private
  def cnpj_must_be_valid
    return if CNPJ.valid?(cnpj)
    errors.add(:cnpj, :invalid)
  end
end

app/controllers/subsidiaries_controller.rb
class SubsidiariesController  < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]
  # before_action :authorize_admin # verificar ser o usuário é admin depois de logar
  # before_action :set_subdisiary, %i[show edit update]

  def index
    @subsidiaries = Subsidiary.all
  end

  def show
    @subsidiary = Subsidiary.find(params[:id])
  end

  def new
    @subsidiary = Subsidiary.new
  end

  def create
    @subsidiary = Subsidiary.new(subsidiary_params)
    if @subsidiary.save
      flash[:notice] = 'Filial criada com sucesso'
      redirect_to @subsidiary
    else  
      render :new
    end
  end

  def edit
    @subsidiary = Subsidiary.find(params[:id])
  end

  def update
    @subsidiary = Subsidiary.find(params[:id])
    if @subsidiary.update(subsidiary_params)
      redirect_to @subsidiary
    else  
      render :edit
    end
  end

  private
  def subsidiary_params
    params.require(:subsidiary).permit(:name, :cnpj, :adress)
  end

  # def authorize_admin
  #   redirect_to root_path, notice: 'Não autorizado' unless current_user.admin?
  # end

end

app/views/subsidiaries/edit.html.erb
<h1>Editar Filial</h1>

<% @subsidiary.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_for @subsidiary do |sd| %>
  <%= sd.label :name %>
  <%= sd.text_field :name %>
  <%= sd.label :cnpj %>
  <%= sd.text_field :cnpj %>
  <%= sd.label :adress %>
  <%= sd.text_field :adress %>
  <%= sd.submit 'Enviar' %>
<% end %>

app/views/subsidiaries/index.html.erb
<h1>Filiais</h1>

<p><%= link_to 'Registrar nova filial', new_subsidiary_path %></p>

<% if @subsidiaries.empty? %>
  <h3>Nenhuma filial cadastrada</h3>
<% else %>

<ul>
  <% @subsidiaries.each do |s| %>
    <li><%= link_to s.name, s %></li>
  <% end %>
</ul>

<% end %>

<p><%= link_to 'Voltar', root_path %></p>

app/views/subsidiaries/new.html.erb
<h1>Registrar Filial</h1>

<%= form_for @subsidiary do |sd| %>
  <%= sd.label :name, 'Nome' %>
  <%= sd.text_field :name %>
  <%= sd.label :cnpj, 'CNPJ' %>
  <%= sd.text_field :cnpj %>
  <%= sd.label :adress, 'Endereço' %>
  <%= sd.text_field :adress %>
  <%= sd.submit 'Enviar' %>
<% end %>

app/views/subsidiaries/show.html.erb
<h1><%= @subsidiary.name %></h1>

<ul>
  <li><%= @subsidiary.cnpj %></li>
  <li><%= @subsidiary.adress %></li>
</ul>

<%= link_to 'Voltar', subsidiaries_path %>
<%= link_to 'Editar', edit_subsidiary_path %>