config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :new, :show, :create, :edit, :update]
  resources :car_categories, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :new, :show, :create]
  resources :rentals, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  
end

app/models/car_category.rb
  class CarCategory < ApplicationRecord
  has_many :car_models
  has_many :cars, through: :car_models
  
  validates :name, presence: true
  validates :daily_rate, presence: true
  validates :car_insurance, presence: true
  validates :third_part_insurance, presence: true
                                        
end

app/controllers/car_categories_controller.rb
class CarCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]
  
  def index
    @car_categories = CarCategory.all
  end

  def show
    @car_category = CarCategory.find(params[:id])
    @car_models = CarModel.where(car_category: @car_category)
  end

  def new
    @car_category = CarCategory.new
  end

  def create 
    @car_category = CarCategory.new(car_category_params)
    @car_category.save
    redirect_to @car_category
  end

  def edit
    @car_category = CarCategory.find(params[:id])
  end

  def update
    @car_category = CarCategory.find(params[:id])
    if @car_category.update(car_category_params)
      redirect_to @car_category
    else 
      render :edit
    end
  end

  private
  def car_category_params
    params.require(:car_category).permit(:name, :daily_rate, :car_insurance, 
                   :third_part_insurance)
  end
end

app/views/car_categories/edit.html.erb
<h1>Editar categoria</h1>

<% @car_category.errors.full_messages.each do |msg| %>
  <%= msg %>
<% end %>

<%= form_for @car_category do |c_c| %>
  <%= c_c.label :name %>
  <%= c_c.text_field :name %>
  <%= c_c.label :daily_rate %>
  <%= c_c.text_field :daily_rate %>
  <%= c_c.label :car_insurance %>
  <%= c_c.text_field :car_insurance %>
  <%= c_c.label :third_part_insurance %>
  <%= c_c.text_field :third_part_insurance %>
  <%= c_c.submit 'Enviar' %>
<% end %>

app/views/car_categories/index.html.erb
<h1>Categoria de Carros</h1>

<%= link_to 'Registrar nova categoria', new_car_category_path %>

<% if @car_categories.empty? %>
  <h3>Nenhuma categoria cadastrada</h3>
<% end %>

  <% @car_categories.each do |c| %>
    <dl>
      <dt>Categoria</dt>
        <dd><%= link_to "Categoria #{c.name}", c %></dd>
      <dt>Diária</dt>
        <dd><%= number_to_currency c.daily_rate %></dd>
    </dl>
  <% end %>

<p><%= link_to 'Voltar', root_path %></p>

app/views/car_categories/new.html.erb
<h1>Registrar Categoria</h1>

<%= form_for @car_category do |c_c| %>
  <%= c_c.label :name, 'Nome' %>
  <%= c_c.text_field :name %>
  <%= c_c.label :daily_rate, 'Diária' %>
  <%= c_c.text_field :daily_rate %>
  <%= c_c.label :car_insurance, 'Seguro' %>
  <%= c_c.text_field :car_insurance %>
  <%= c_c.label :third_part_insurance, 'Seguro de terceiros' %>
  <%= c_c.text_field :third_part_insurance %>
  <%= c_c.submit 'Enviar' %>
<% end %>

app/views/car_categories/show.html.erb
<h1>Categoria <%= @car_category.name %></h1>
<dl>
  <dt>Diária:</dt>
    <dd><%= number_to_currency @car_category.daily_rate %></dd>
  <dt>Seguro do Carro:</dt>
    <dd><%= number_to_currency @car_category.car_insurance %></dd>
  <dt>Seguro para Terceiros:</dt>
    <dd><%= number_to_currency @car_category.third_part_insurance %></dd>
</dl>

<%= link_to 'Editar', edit_car_category_path %>

<h3>Modelos de Carros</h3>

<% @car_category.car_models.each do |car_model| %>
  <%= link_to car_model.name, car_model %>
<% end %>

<p><%= link_to 'Voltar', car_categories_path %></p>