config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :new, :show, :create, :edit, :update]
  resources :car_categories, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :new, :show, :create]
  resources :rentals, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :customer
  belongs_to :car_category
  has_one :car_rental
  has_one :car, through: :car_rental

  before_create :generate_code

  enum status: { scheduled: 0, ongoing: 5 }

  private
  def generate_code
    self.code = SecureRandom.alphanumeric(6).upcase
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]

  def index
    @rentals = Rental.all
  end

  def show
    @rental = Rental.find(params[:id])
  end

  def new
    @rental = Rental.new
    @customers = Customer.all
    @car_categories = CarCategory.all
  end

  def create
    @rental = Rental.create(rental_params)
    #@rental.save!
    redirect_to rentals_path
  end 

  def search
    @q = params[:q]
    @rental = Rental.find_by(code: @q.upcase)
=begin  
    @rental = Rental.find_by(code: params[:q].upcase)  
    if @rental.blank? || params[:q].blank?
      @rentals = Rental.all
      flash.now[:alert] = "Nenhum resultado encontrado para: #{params[:q]}"
      render :index
    end
=end
  end

  private
  def rental_params
    params.require(:rental).permit(:start_date, :end_date, 
                                   :customer_id, :car_category_id)
  end
end

app/views/rentals/_rental.html.erb
<dl>
  <dt><%= Rental.human_attribute_name(:code) %></dt>
  <dd><%= rental.code %></dd>
  <dt>Data de início:</dt>
  <dd><%= l rental.start_date %></dd>
  <dt>Data de término:</dt>
  <dd><%= l rental.end_date %></dd>
  <dt>Cliente:</dt>
  <dd><%= rental.customer.name %></dd>
  <dt>Categoria:</dt>
  <dd><%= rental.car_category.name %></dd>
  <dt>Status:</dt>
  <dd><%= Rental.human_attribute_name("status.#{rental.status}") %></dd>
</dl>

app/views/rentals/index.html.erb
<h1>Locações</h1>

<%= link_to 'Registrar nova locação', new_rental_path %>

<%= form_with url: search_rentals_path, local: true, method: :get do |f| %>
  <%= f.label :q, 'Código '%>
  <%= f.text_field :q %>
  <%= f.submit 'Buscar' %>
<% end %>

<%= render @rentals %>

app/views/rentals/new.html.erb
<h1>Nova Locação</h1>

<%= form_with model: @rental, local: true do |f| %>
  <%= f.label :start_date, 'Data de início' %>
  <%= f.date_field :start_date %>
  <%= f.label :end_date, 'Data de término' %>
  <%= f.date_field :end_date %>
  <%= f.label :customer_id, 'Cliente' %>
  <%= f.collection_select :customer_id, @customers, :id, :name %>
  <%= f.label :car_category_id, 'Categoria' %>
  <%= f.collection_select :car_category_id, @car_categories, :id, :name %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/rentals/search.html.erb
<% if @rental %>
  <dl>
    <dt>Código</dt>
    <dd><%= @rental.code %></dd>
    <dt>Data de início:</dt>
    <dd><%= l @rental.start_date %></dd>
    <dt>Data de término:</dt>
    <dd><%= l @rental.end_date %></dd>
    <dt>Cliente:</dt>
    <dd><%= @rental.customer.name %></dd>
    <dt>Categoria:</dt>
    <dd><%= @rental.car_category.name %></dd>
  </dl>
  <%= link_to 'Iniciar', new_rental_car_rental_path(@rental) %>
<% else %>
  <p><%= "Nenhum resultado encontrado para: #{@q}" %></p>
<% end %>

app/views/rentals/show.html.erb
<%= render @rental%>

  <% if @rental.car_rental.present? %>
    <p>Data de início da locação: <%= l @rental.car_rental.created_at, format: :long %></p>
    <p>Carro: <%= @rental.car_rental.car.license_plate %></p>
    <p>Cliente: <%= @rental.customer.email %></p>
    <p>Locação iniciada por: <%= @rental.car_rental.user.email %></p>
  <% end %>