config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :manufacturers
  resources :subsidiaries, only: [:index, :new, :show, :create, :edit, :update]
  resources :car_categories, only: [:index, :new, :show, :create, :edit, :update]
  resources :customers, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
  end
  resources :car_models, only: [:index, :new, :show, :create]
  resources :rentals, only: [:index, :new, :show, :create] do
    get 'search', on: :collection
    resources :car_rentals, only: [:new, :create]
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalCars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Início', root_path %>
        <%= link_to 'Filiais', subsidiaries_path %>
        <%= link_to 'Clientes', customers_path %>
        <%= link_to 'Fabricantes', manufacturers_path %>
        <%= link_to 'Categorias de Carros', car_categories_path %>
        <%= link_to 'Modelos de Carros', car_models_path %>
        <%= link_to 'Locações', rentals_path %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to'Entrar', new_user_session_path %>
      <% end %>
    </nav>
    <%= flash[:notice] %>
    <%= flash[:alert]%>
    <%= yield %>
  </body>
</html>